### ISSUE TITLE
Butter stick stand-offs/inserts

### ISSUE THREAD

**Issue by equalunique** [germ/gergo-case#1]
what type of stand-offs or inserts are intended to be used with the butters stick case files?

**Comment by germ** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hey! Just got in contact with the designer, It should take M3 screws and it's a floating PCB type.                                                                                                                                                                                                                                                                                                                         From: notifications@github.comSent: June 19, 2019 10:44 AMTo: gergo-case@noreply.github.comReply to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [germ/gergo-case] Butter stick stand-offs/inserts (#1)  what type of stand-offs or inserts are intended to be used with the butters stick case files?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by equalunique** [comment]
Interesting! So then M3 screws thread directly through the top and bottom plate into the middle layer? No brass inserts or other brass required?

**Comment by germ** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  I'm actually not sure,  a user in Discord made it!I've attached his information and some servers he's in. He'd be very exited to see photos when you're done!                                                                                                                                                                                                                                                                                                                         From: notifications@github.comSent: June 19, 2019 1:28 PMTo: gergo-case@noreply.github.comReply to: reply@reply.github.comCc: jeremythegeek@gmail.com; comment@noreply.github.comSubject: Re: [germ/gergo-case] Butter stick stand-offs/inserts (#1)  Interesting! So then M3 screws thread directly through the top and bottom plate into the middle layer? No brass inserts or other brass required?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
